apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  labels:
    app: auth
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth
  
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth-container
          image: yujiarima/auth-service:v1
          ports:
            - containerPort: 8081
          livenessProbe:
            httpGet:
              path: /auth/healthz
              port: 8081
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /auth/readyz
              port: 8081
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 5
          startupProbe:
            httpGet:
              path: /auth/startupz
              port: 8081
            failureThreshold: 5
            initialDelaySeconds: 5
            periodSeconds: 5

