apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  labels:
    app: user
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user
  
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user-container
          image:  yujiarimadev/user-service:v3
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /user/healthz
              port: 8080
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /user/readyz
              port: 8080
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 5
          startupProbe:
            httpGet:
              path: /user/startupz
              port: 8080
            failureThreshold: 5
            initialDelaySeconds: 5
            periodSeconds: 5
          

